// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5NWNSlF6ynRMBQLTFwGt_BSd29XP-9k4',
    appId: '1:810588546790:web:0d21c81fffcfa5f469fd27',
    messagingSenderId: '810588546790',
    projectId: 'afrahdz',
    authDomain: 'afrahdz.firebaseapp.com',
    storageBucket: 'afrahdz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9-cD4NBqCZ1i1Za4jlD3ZPFvkpzBcRcE',
    appId: '1:810588546790:android:306df89ef07c317b69fd27',
    messagingSenderId: '810588546790',
    projectId: 'afrahdz',
    storageBucket: 'afrahdz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG53QNtKw_FJd1rB_PHC6x8A8ED13UN48',
    appId: '1:810588546790:ios:1d93557c614dec0f69fd27',
    messagingSenderId: '810588546790',
    projectId: 'afrahdz',
    storageBucket: 'afrahdz.firebasestorage.app',
    iosBundleId: 'com.example.afrahdz',
  );
}
